changelog:
  exclude:
    labels:
      - chore
      - ignore-for-release
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
        - semver-major
    - title: Security fixes
      labels:
        - security
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
