export const receive = {
  receive_title: 'Receive',
  receive_unshieldedTab: 'Unshielded',
  receive_shieldedTab: 'Shielded',
  receive_addressCopied: 'Address copied',
  receive_shieldedAddressOf: '$1 · Shielded address',
  receive_unshieldedAddressOf: '$1 · Unshielded address',
  receive_addressUnavailable: 'Address unavailable',
  receive_copyAddress: 'Copy address',
  receive_shieldedNote: 'Only send Midnight native tokens here. Anything else may be lost.',
  receive_unshieldedNote: 'Transfers here are visible on the network. Anyone with the address can see amounts.',
  receive_dustTab: 'DUST',
  receive_dustAddressOf: 'DUST address of $1',
  receive_dustNote:
    'Nobody can send you DUST — it is generated by the NIGHT or cNIGHT you hold. This is the address that generation pays to, so use it when registering from another wallet.',
} as const;
