// API-key store for the daemon's stage-2 AuthN. Keys live as
// individual JSON files under ~/.moth/api-keys/ (mode 0700 dir,
// 0600 files). Each file is one record:
//
//   {
//     "id":           "<8-char hex prefix>",
//     "label":        "ci-bot",
//     "salt":         "<hex>",
//     "hashedSecret": "<hex>",
//     "createdAt":    "<iso>",
//     "revokedAt":    "<iso?>",
//     "scopes":       ["read", "write"]   // reserved; stage-2.5
//   }
//
// The token presented on the wire is `<id>.<secret-hex>`; the
// server splits on the dot, looks up the record by id, and
// timing-safe-compares sha256(salt || secret) against
// `hashedSecret`. Plain SHA-256 is fine because the secret is 32
// bytes of CSPRNG output — brute force is not viable. No need
// for Argon2id's CPU/memory cost on a high-entropy secret; the
// cost there exists to slow human-passphrase guessing.

import {randomBytes, timingSafeEqual, createHash} from 'node:crypto';
import {existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync} from 'node:fs';
import {homedir} from 'node:os';
import {join, resolve, sep} from 'node:path';

/**
 * The on-disk id of a key is exactly 8 lowercase hex chars — derived
 * from the first 4 random bytes of the key's secret. Tokens that
 * don't parse to this shape can never have been generated by us, so
 * every read/write path validates against this regex BEFORE touching
 * the filesystem. Without it, a malicious token like
 * `../../etc/passwd.<anything>` would let `read()` attempt to stat
 * arbitrary files inside the user's home — a path-traversal primitive
 * that future bugs could compound into a real exploit even though
 * the JSON.parse + hash check would still reject the contents.
 */
const ID_RE = /^[0-9a-f]{8}$/;

export interface ApiKeyRecord {
  readonly id: string;
  readonly label: string;
  readonly salt: string;
  readonly hashedSecret: string;
  readonly createdAt: string;
  readonly revokedAt?: string;
  /** Scopes this key holds. Defaults to ['write'] (full daemon access)
   *  on records that predate scopes. Enforced by the daemon's
   *  per-method gate (server.ts): a read-only key is rejected from
   *  every write verb. */
  readonly scopes?: readonly string[];
}

export interface ApiKeyGenerated {
  readonly record: ApiKeyRecord;
  /** The plaintext token `<id>.<secret-hex>`. Returned ONCE to the
   *  caller (the `key gen` CLI command surfaces it on stdout); the
   *  store never persists this value. */
  readonly token: string;
}

export interface ApiKeyAuthResult {
  readonly apiKeyId: string;
  readonly label: string;
  readonly scopes: readonly string[];
}

export class ApiKeyStore {
  private readonly dir: string;

  constructor(opts: {dir?: string} = {}) {
    this.dir = opts.dir ?? join(homedir(), '.moth', 'api-keys');
    mkdirSync(this.dir, {recursive: true, mode: 0o700});
  }

  /**
   * Generate, persist, and return a new API key. The plaintext token
   * is surfaced ONCE in the returned `token` field and never
   * persisted — once the CLI has shown it to the operator there is
   * no way to recover it.
   *
   * `scopes` defaults to `['write']` (full daemon access) so
   * existing call sites that don't pass it keep their previous
   * semantics. A read-only key passes `['read']`; a key that needs
   * both passes `['read', 'write']`.
   */
  generate(label: string, scopes: readonly string[] = ['write']): ApiKeyGenerated {
    if (!label.trim()) throw new Error('API key label is required');
    const VALID = new Set(['read', 'write']);
    const normalised = Array.from(new Set(scopes.map((s) => s.trim()))).filter((s) => s.length > 0);
    if (normalised.length === 0) {
      throw new Error('at least one scope is required (read, write, or both)');
    }
    for (const s of normalised) {
      if (!VALID.has(s)) {
        throw new Error(`unknown scope "${s}"; valid: read, write`);
      }
    }
    const secretBytes = randomBytes(32);
    const id = secretBytes.subarray(0, 4).toString('hex'); // 8-char hex id
    const salt = randomBytes(16).toString('hex');
    const hashedSecret = hashSecret(salt, secretBytes.toString('hex'));
    const record: ApiKeyRecord = {
      id,
      label: label.trim(),
      salt,
      hashedSecret,
      createdAt: new Date().toISOString(),
      scopes: normalised,
    };
    this.write(record);
    return {record, token: `${id}.${secretBytes.toString('hex')}`};
  }

  /**
   * Verify a wire token. Returns the auth result on success or null
   * on any failure (unknown id, wrong secret, revoked key). Always
   * runs the hash compare even when the id is unknown so the timing
   * profile doesn't leak id presence.
   */
  verify(token: string): ApiKeyAuthResult | null {
    const dot = token.indexOf('.');
    if (dot <= 0 || dot === token.length - 1) {
      // Still hash a dummy to keep timing stable.
      timingSafeCompareHex(
        hashSecret('00'.repeat(16), '00'.repeat(32)),
        hashSecret('00'.repeat(16), '00'.repeat(32)),
      );
      return null;
    }
    const id = token.slice(0, dot);
    const secret = token.slice(dot + 1);
    // Validate the id shape BEFORE any filesystem use. An id that
    // doesn't match the canonical 8-hex format could never have been
    // generated by us, so we reject it as failed-auth without
    // touching the disk. Defense-in-depth against path-traversal
    // tokens like `../../etc/passwd.<anything>`.
    if (!ID_RE.test(id)) {
      timingSafeCompareHex(
        hashSecret('00'.repeat(16), secret),
        hashSecret('00'.repeat(16), '00'.repeat(32)),
      );
      return null;
    }
    const record = this.read(id);
    if (!record || record.revokedAt) {
      // Run a dummy hash to keep the timing profile uniform.
      timingSafeCompareHex(
        hashSecret('00'.repeat(16), secret),
        hashSecret('00'.repeat(16), '00'.repeat(32)),
      );
      return null;
    }
    const presented = hashSecret(record.salt, secret);
    if (!timingSafeCompareHex(presented, record.hashedSecret)) return null;
    return {
      apiKeyId: record.id,
      label: record.label,
      scopes: record.scopes ?? ['write'],
    };
  }

  list(): readonly ApiKeyRecord[] {
    if (!existsSync(this.dir)) return [];
    const out: ApiKeyRecord[] = [];
    for (const name of readdirSync(this.dir)) {
      if (!name.endsWith('.key')) continue;
      try {
        out.push(JSON.parse(readFileSync(join(this.dir, name), 'utf-8')) as ApiKeyRecord);
      } catch {
        /* skip unreadable / malformed entries */
      }
    }
    return out;
  }

  /**
   * Mark a key revoked. Returns the updated record, or null if no
   * key with that id exists. Revoked records are kept on disk so
   * audit lines reference a real id.
   */
  revoke(id: string): ApiKeyRecord | null {
    const existing = this.read(id);
    if (!existing) return null;
    if (existing.revokedAt) return existing;
    const updated: ApiKeyRecord = {
      ...existing,
      revokedAt: new Date().toISOString(),
    };
    this.write(updated);
    return updated;
  }

  /** Whether the store currently has at least one non-revoked key.
   *  Used by `daemon serve` to refuse a TCP bind that would have no
   *  way to authenticate any caller. */
  hasActiveKey(): boolean {
    return this.list().some((r) => !r.revokedAt);
  }

  /** Filesystem location — exposed for tests + CLI status output. */
  get directory(): string {
    return this.dir;
  }

  private read(id: string): ApiKeyRecord | null {
    // Belt-and-suspenders: re-validate at the IO boundary. Callers
    // are supposed to gate on ID_RE before getting here, but a
    // future refactor could miss a path. Cheap to check twice.
    if (!ID_RE.test(id)) return null;
    const path = join(this.dir, `${id}.key`);
    if (!isInside(this.dir, path)) return null;
    if (!existsSync(path)) return null;
    try {
      return JSON.parse(readFileSync(path, 'utf-8')) as ApiKeyRecord;
    } catch {
      return null;
    }
  }

  private write(record: ApiKeyRecord): void {
    if (!ID_RE.test(record.id)) {
      throw new Error(`refusing to write key with malformed id: ${record.id}`);
    }
    const path = join(this.dir, `${record.id}.key`);
    if (!isInside(this.dir, path)) {
      throw new Error(`refusing to write key outside ${this.dir}`);
    }
    writeFileSync(path, JSON.stringify(record, null, 2) + '\n', {mode: 0o600});
  }
}

/**
 * True iff `child`, resolved against the filesystem, is the same as
 * or a descendant of `parent`. Used as a defense-in-depth check
 * after the id regex — even if `..` somehow appeared in a path
 * (e.g. because Node added a quirk), this would catch it before any
 * read/write touched a file outside the api-keys directory.
 */
function isInside(parent: string, child: string): boolean {
  const p = resolve(parent);
  const c = resolve(child);
  return c === p || c.startsWith(p + sep);
}

function hashSecret(saltHex: string, secretHex: string): string {
  const h = createHash('sha256');
  h.update(Buffer.from(saltHex, 'hex'));
  h.update(Buffer.from(secretHex, 'hex'));
  return h.digest('hex');
}

function timingSafeCompareHex(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  const ab = Buffer.from(a, 'hex');
  const bb = Buffer.from(b, 'hex');
  if (ab.length !== bb.length) return false;
  return timingSafeEqual(ab, bb);
}
