// Daemon server: binds a Unix-domain socket, applies L1 filesystem perms,
// accepts client connections, and dispatches RPC requests to registered
// handlers.
//
// Threat model addressed by this layer:
//   - Other users on the same machine connecting to the socket — blocked
//     at the kernel by 0600 socket-file perms inside a 0700 directory,
//     both owned by the daemon's UID.
//   - Stale socket file from a crashed previous daemon — detected on bind
//     and removed only after probing that no one is actually listening.
//
// Per-operation confirmation (L3) is the handler's responsibility — server
// passes the connection context through so handlers can ask the TUI to
// surface a modal and only return after user consent.

import {createServer, type Server, type Socket} from 'node:net';
import {chmod, mkdir, stat, unlink, access} from 'node:fs/promises';
import {createConnection} from 'node:net';
import {dirname} from 'node:path';
import {
  encodeFrame,
  FrameDecoder,
  PROTOCOL_VERSION,
  DaemonProtocolError,
  type Frame,
  type RequestFrame,
  type RpcErrorCode,
} from './protocol.js';

/**
 * Transport binding. Stage 1 supports only `unix`. Stage 2 adds
 * `tcp` for loopback / private-network exposure; the JSON-RPC frame
 * format and verb surface stay identical. See
 * docs/spec/wallet-service/01-architecture.md D-ARCH-1.
 */
export type DaemonBind =
  | {readonly transport: 'unix'; readonly socketPath: string}
  | {readonly transport: 'tcp'; readonly host: string; readonly port: number};

/**
 * Stage-2.5 scope set. Each API key declares which of these it
 * holds; the daemon's per-method gate checks the required scope
 * (declared by the handler factory) against the connection's set.
 *
 *   'read'  → getState (and any other read-only verbs we add)
 *   'write' → every L3-gated write verb (transfer, deploy, call,
 *             dust, maintenance, submitTransaction, clearSyncCache)
 *
 * Unix connections without an auth handler skip the scope check —
 * kernel UID is the AuthN and granular scoping inside a single UID
 * is theatre. The check only fires on connections that actually
 * authenticated through `auth`.
 */
export type Scope = 'read' | 'write';

export type ConnectionContext = {
  /** Numeric id local to the daemon; useful for logs. */
  readonly id: number;
  /** Transport this connection arrived on. Reserved for stage-2
   *  AuthN to enforce "Bearer required on TCP, not on Unix" rules. */
  readonly remote: 'unix' | 'tcp';
  /** Best-effort peer label — `unix` for Unix sockets, the
   *  `host:port` of the peer for TCP. */
  readonly peer?: string;
  /** API key id once the `auth` RPC succeeds on this connection.
   *  Absent on the Unix transport (kernel UID is the AuthN there)
   *  and on TCP connections that haven't authenticated yet — those
   *  are blocked from every method besides `auth` and `version`. */
  apiKeyId?: string;
  /** Friendly label of the authenticated key, stamped at `auth`
   *  time. Surfaced in audit log + connect logs. */
  apiKeyLabel?: string;
  /** Scope set carried by the authenticated key. Used by the
   *  per-method gate to enforce read vs write. */
  scopes?: readonly Scope[];
};

/**
 * Stage-2 AuthN hook. Takes the wire token (`<id>.<secret>` shape
 * generated by `moth daemon key gen`), returns the authenticated
 * identity on success or null on any failure. The server only
 * accepts an `auth` RPC on a connection when this handler is set;
 * once it has accepted one, all other methods carry the resulting
 * `apiKeyId` in their ConnectionContext.
 *
 * Unix-transport daemons typically run without an auth handler —
 * kernel UID on the 0600 socket is sufficient. TCP daemons MUST
 * supply one or `startDaemon` refuses to bind.
 */
export type AuthHandler = (token: string) => Promise<AuthResult | null> | AuthResult | null;

export interface AuthResult {
  readonly apiKeyId: string;
  readonly label?: string;
  readonly scopes?: readonly string[];
}

export type RpcHandler<P = unknown, R = unknown> = ((
  params: P,
  ctx: ConnectionContext,
) => Promise<R> | R) & {
  /**
   * Scope required to invoke this handler when an auth handler is
   * configured. When absent, defaults to `'write'` — every
   * historically-existing handler is treated as a write op so a
   * read-only key cannot accidentally unlock spend verbs. The
   * `version` and `auth` built-ins are always reachable regardless
   * of scope (the gate special-cases them).
   */
  scope?: Scope;
};

export interface DaemonOptions {
  /**
   * Transport binding. Use either this OR the legacy `socketPath`
   * field (mutually exclusive). When both are absent, startDaemon
   * throws.
   */
  readonly bind?: DaemonBind;
  /**
   * Legacy Unix-socket path. Equivalent to
   * `bind: {transport: 'unix', socketPath}`. Kept for backwards
   * compatibility with stage-1 call sites; new code should prefer
   * `bind`.
   */
  readonly socketPath?: string;
  /** Map of method name → handler. The reserved method `version` is
   *  installed automatically and cannot be overridden. */
  readonly handlers: Readonly<Record<string, RpcHandler>>;
  /** Daemon build identifier surfaced in the `version` handshake. */
  readonly daemonVersion: string;
  /** Optional logger hook. Defaults to silent. */
  readonly onLog?: (level: 'info' | 'warn' | 'error', msg: string) => void;
  /**
   * Stage-2 AuthN handler. When set, the daemon installs an `auth`
   * RPC and gates every other method behind a successful auth call
   * on the same connection. When omitted, the daemon accepts every
   * connection unauthenticated (the stage-1 / Unix-transport model).
   *
   * **TCP transport requires this**: `startDaemon` throws if
   * `bind.transport === 'tcp'` and `auth` is undefined. Without it,
   * exposing the daemon's write verbs over the network would have
   * no AuthN at all.
   */
  readonly auth?: AuthHandler;
  /**
   * Fired on every `auth` RPC outcome so the host can write a
   * permanent audit record of authentication successes and failures
   * (the live log alone leaves no lasting trail of break-in attempts).
   */
  readonly onAuthEvent?: (event: {
    readonly outcome: 'success' | 'failure';
    readonly apiKeyId?: string;
    readonly peer?: string;
  }) => void;
  /**
   * Fired on inbound client activity (connect + each data chunk). The
   * host uses this to drive an idle auto-lock so a long-running daemon
   * isn't a permanently-unlocked key.
   */
  readonly onActivity?: () => void;
}

export interface DaemonHandle {
  /** Normalised binding the daemon listens on. */
  readonly bind: DaemonBind;
  /**
   * Legacy: Unix socket path if `bind.transport === 'unix'`, else
   * empty string. Preserved so existing callers reading
   * `handle.socketPath` keep working.
   */
  readonly socketPath: string;
  /**
   * Operator-friendly label of where the daemon is listening, e.g.
   * `unix:///Users/.../wallet.sock` or `tcp://127.0.0.1:8765`.
   */
  readonly listenAddress: string;
  /** Stop accepting new connections, close all active ones, and
   *  clean transport-specific artifacts (the Unix socket file).
   *  Resolves once everything is torn down. */
  close(): Promise<void>;
}

export async function startDaemon(opts: DaemonOptions): Promise<DaemonHandle> {
  const {handlers, daemonVersion} = opts;
  const log = opts.onLog ?? (() => {});

  // Normalise the binding. Accept either `bind` (new shape) or the
  // legacy `socketPath` string.
  const bind: DaemonBind = opts.bind
    ? opts.bind
    : opts.socketPath
      ? {transport: 'unix', socketPath: opts.socketPath}
      : (() => {
          throw new Error('startDaemon: either `bind` or `socketPath` is required');
        })();

  // Stage-2 invariant: TCP must have an auth handler. Without it the
  // operator would be exposing every write verb (transfer, deploy,
  // call, dust, maintenance) to anyone who can reach the port.
  // Unix transport stays optional — kernel UID on the 0600 socket
  // is sufficient AuthN for the local-only model.
  if (bind.transport === 'tcp' && !opts.auth) {
    throw new Error(
      'startDaemon: TCP transport requires an `auth` handler. Provision API keys via `moth daemon key gen` and pass the resulting ApiKeyStore-backed handler.',
    );
  }

  // Per-transport pre-listen work (Unix only — directory perms,
  // stale-file reap).
  if (bind.transport === 'unix') {
    await ensureSocketDir(dirname(bind.socketPath));
    await reapStaleSocket(bind.socketPath, log);
  }

  const builtins: Record<string, RpcHandler> = {
    version: () => ({protocol: PROTOCOL_VERSION, daemon: daemonVersion}),
  };
  if (opts.auth) {
    builtins.auth = async (rawParams: unknown, ctx: ConnectionContext) => {
      const params = rawParams as {token?: unknown};
      if (typeof params?.token !== 'string' || params.token.length === 0) {
        throw new DaemonProtocolError('INVALID_PARAMS', 'auth.token must be a non-empty string');
      }
      const result = await opts.auth!(params.token);
      if (!result) {
        opts.onAuthEvent?.({outcome: 'failure', peer: ctx.peer});
        throw new DaemonProtocolError('UNAUTHORIZED', 'auth failed');
      }
      opts.onAuthEvent?.({outcome: 'success', apiKeyId: result.apiKeyId, peer: ctx.peer});
      // Mutate the per-connection context. attachConnectionHandlers
      // hands the same `ctx` object to every subsequent dispatch, so
      // gating later methods on `ctx.apiKeyId` is sufficient.
      ctx.apiKeyId = result.apiKeyId;
      ctx.apiKeyLabel = result.label;
      // Normalise scopes to the typed set. Unknown scopes are
      // silently dropped — they could never satisfy a known
      // requirement anyway.
      const VALID: Scope[] = ['read', 'write'];
      const parsed = (result.scopes ?? ['write'])
        .filter((s): s is Scope => (VALID as string[]).includes(s));
      ctx.scopes = parsed;
      log('info', `client ${ctx.id} authed as key ${result.apiKeyId} (${result.label ?? '-'}) scopes=[${parsed.join(',')}]`);
      return {apiKeyId: result.apiKeyId, label: result.label, scopes: parsed};
    };
  }
  const allHandlers: Record<string, RpcHandler> = {...handlers, ...builtins};

  // Methods always reachable without auth. `version` is the
  // handshake (clients call it before auth to verify protocol
  // version), `auth` itself obviously can't require auth.
  const ALWAYS_OPEN = new Set(['version', 'auth']);

  // Wrap every other handler with an auth + scope check when auth
  // is on. The auth check is per-call on the connection context (not
  // per method registration), so a single connection that
  // successfully authenticates unlocks every method it has scope for
  // for the rest of its lifetime. The scope check looks at the
  // handler's declared `scope` (defaulting to 'write' when absent,
  // so a new handler without the annotation cannot be accidentally
  // called by a read-only key).
  const gated: Record<string, RpcHandler> = {};
  for (const [name, h] of Object.entries(allHandlers)) {
    if (ALWAYS_OPEN.has(name) || !opts.auth) {
      gated[name] = h;
      continue;
    }
    const required: Scope = h.scope ?? 'write';
    const wrapper: RpcHandler = async (params, ctx) => {
      if (!ctx.apiKeyId) {
        throw new DaemonProtocolError(
          'UNAUTHORIZED',
          `method "${name}" requires authentication — call \`auth\` with a valid \`<id>.<secret>\` token first`,
        );
      }
      if (ctx.scopes && !ctx.scopes.includes(required)) {
        throw new DaemonProtocolError(
          'UNAUTHORIZED',
          `method "${name}" requires the "${required}" scope; key ${ctx.apiKeyId} has [${(ctx.scopes ?? []).join(', ')}]`,
        );
      }
      return h(params, ctx);
    };
    // Forward the scope annotation in case a future inspector reads
    // it back off the gated map.
    wrapper.scope = required;
    gated[name] = wrapper;
  }

  const server = createServer();
  let nextConnId = 1;
  const liveSockets = new Set<Socket>();

  server.on('connection', (sock) => {
    const remote: ConnectionContext['remote'] = bind.transport === 'tcp' ? 'tcp' : 'unix';
    const peer =
      bind.transport === 'tcp'
        ? `${sock.remoteAddress ?? '?'}:${sock.remotePort ?? '?'}`
        : 'unix';
    const ctx: ConnectionContext = {id: nextConnId++, remote, peer};
    liveSockets.add(sock);
    opts.onActivity?.();
    log('info', `client ${ctx.id} connected (${peer})`);
    attachConnectionHandlers(sock, ctx, gated, log, opts.onActivity);
    sock.on('close', () => {
      liveSockets.delete(sock);
      log('info', `client ${ctx.id} disconnected`);
    });
  });

  server.on('error', (err) => {
    log('error', `daemon server error: ${err.message}`);
  });

  await new Promise<void>((resolve, reject) => {
    const onListen = () => {
      server.off('error', onError);
      resolve();
    };
    const onError = (err: Error) => {
      server.off('listening', onListen);
      reject(err);
    };
    server.once('listening', onListen);
    server.once('error', onError);
    if (bind.transport === 'unix') {
      server.listen(bind.socketPath);
    } else {
      // TCP: bind to the requested host (caller is responsible for
      // restricting to loopback — 127.0.0.1 — at stage 2; only
      // stage-3 deployments behind a reverse proxy should bind 0.0.0.0
      // and rely on the proxy's firewall + AuthN for safety).
      server.listen(bind.port, bind.host);
    }
  });

  let listenAddress: string;
  if (bind.transport === 'unix') {
    // L1: tighten the socket file to owner-only access. createServer
    // doesn't do this for us; the file is created with the process
    // umask, which is typically too permissive. The TCP transport
    // has no equivalent — relies on loopback bind + AuthN at stage 2.
    await chmod(bind.socketPath, 0o600);
    listenAddress = `unix://${bind.socketPath}`;
  } else {
    listenAddress = `tcp://${bind.host}:${bind.port}`;
  }
  log('info', `daemon listening at ${listenAddress}`);

  return {
    bind,
    socketPath: bind.transport === 'unix' ? bind.socketPath : '',
    listenAddress,
    async close() {
      log('info', 'daemon shutting down');
      for (const sock of liveSockets) sock.destroy();
      liveSockets.clear();
      await new Promise<void>((resolve) => server.close(() => resolve()));
      if (bind.transport === 'unix') {
        await unlink(bind.socketPath).catch(() => {});
      }
    },
  };
}

async function ensureSocketDir(dir: string): Promise<void> {
  await mkdir(dir, {recursive: true, mode: 0o700});
  // chmod separately so that an existing dir gets its perms tightened too;
  // mkdir({mode}) only applies to newly-created directories.
  await chmod(dir, 0o700);
}

/**
 * If the socket file already exists, probe whether anyone is actually
 * listening. If a peer accepts our connect, fail loud — another daemon is
 * alive. If the connect is refused or times out quickly, treat the file as
 * a leftover from a crashed previous instance and unlink it.
 */
async function reapStaleSocket(
  socketPath: string,
  log: (level: 'info' | 'warn' | 'error', msg: string) => void,
): Promise<void> {
  try {
    await access(socketPath);
  } catch {
    return; // no file, nothing to reap
  }

  const alive = await probeListener(socketPath);
  if (alive) {
    throw new Error(
      `another moth daemon is already listening at ${socketPath}; refusing to bind`,
    );
  }
  log('warn', `removing stale socket at ${socketPath}`);
  await unlink(socketPath).catch(() => {});
}

function probeListener(socketPath: string): Promise<boolean> {
  return new Promise<boolean>((resolve) => {
    const probe = createConnection(socketPath);
    const cleanup = (alive: boolean) => {
      probe.removeAllListeners();
      probe.destroy();
      resolve(alive);
    };
    probe.once('connect', () => cleanup(true));
    probe.once('error', () => cleanup(false));
    // Defensive: 2s is plenty for a local socket; if we hang past that
    // assume something is wrong and treat as dead so the daemon can boot.
    setTimeout(() => cleanup(false), 2000).unref();
  });
}

function attachConnectionHandlers(
  sock: Socket,
  ctx: ConnectionContext,
  handlers: Readonly<Record<string, RpcHandler>>,
  log: (level: 'info' | 'warn' | 'error', msg: string) => void,
  onActivity?: () => void,
): void {
  const decoder = new FrameDecoder();

  sock.on('data', async (chunk: Buffer) => {
    onActivity?.();
    let frames: Frame[];
    try {
      frames = decoder.push(chunk);
    } catch (err) {
      log('warn', `client ${ctx.id} sent malformed frame: ${(err as Error).message}`);
      sock.destroy();
      return;
    }

    for (const frame of frames) {
      if (frame.type !== 'request') {
        // Servers don't currently accept response frames from clients —
        // the protocol is request/response, not bidirectional RPC.
        sendFrame(sock, {
          id: frame.id,
          type: 'response',
          error: {code: 'INVALID_REQUEST', message: 'server only accepts requests'},
        });
        continue;
      }
      await dispatchRequest(sock, ctx, frame, handlers, log);
    }
  });

  sock.on('error', (err) => {
    log('warn', `client ${ctx.id} socket error: ${err.message}`);
  });
}

async function dispatchRequest(
  sock: Socket,
  ctx: ConnectionContext,
  req: RequestFrame,
  handlers: Readonly<Record<string, RpcHandler>>,
  log: (level: 'info' | 'warn' | 'error', msg: string) => void,
): Promise<void> {
  const handler = handlers[req.method];
  if (!handler) {
    sendFrame(sock, errorResponse(req.id, 'METHOD_NOT_FOUND', `no handler for ${req.method}`));
    return;
  }
  try {
    const result = await handler(req.params, ctx);
    sendFrame(sock, {id: req.id, type: 'response', result});
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    // Preserve the handler's intended RpcErrorCode when it threw a
    // DaemonProtocolError — otherwise clients can't distinguish e.g.
    // UNAUTHORIZED, INVALID_PARAMS, METHOD_NOT_FOUND from a generic
    // INTERNAL_ERROR. Any other error class is mapped to INTERNAL_ERROR
    // so a buggy handler can't leak unexpected codes onto the wire.
    const code: RpcErrorCode = err instanceof DaemonProtocolError ? err.code : 'INTERNAL_ERROR';
    log('warn', `client ${ctx.id} method ${req.method} threw [${code}]: ${message}`);
    sendFrame(sock, errorResponse(req.id, code, message));
  }
}

function errorResponse(id: string, code: RpcErrorCode, message: string): Frame {
  return {id, type: 'response', error: {code, message}};
}

function sendFrame(sock: Socket, frame: Frame): void {
  if (sock.destroyed || !sock.writable) return;
  try {
    sock.write(encodeFrame(frame));
  } catch {
    // socket errors will surface via the 'error' listener; nothing to do here
  }
}

/** Test-only helper. Exported for unit tests that need to bind a temporary
 *  socket without ensuring the directory exists. Production code should
 *  always go through startDaemon. */
export async function _stat(path: string): Promise<{mode: number}> {
  const s = await stat(path);
  return {mode: s.mode};
}

export type {Server};
