// Guard: commands that declare positional arguments must be able to receive them.
//
// With `topicSeparator: " "`, oclif decides where the command id ends by walking
// argv and stopping when the id it has matched so far names a command that takes
// positional arguments (`collateSpacedCmdIDFromArgs` → `hasArgs()`). It answers
// that question from its command cache, which is populated from
// `oclif.manifest.json`. Without a manifest, `hasArgs()` is false for every
// command, so oclif keeps swallowing tokens as command-path segments:
//
//   moth mint 1              -> Error: command mint 1 not found
//   moth config get prover   -> Error: command config get prover not found
//   moth state <address>     -> Error: command state <address> not found
//
// Six commands were affected and their documented usage did not work (#53).
// The manifest is generated by `yarn build`; this fails if that stops happening,
// or if a command's args go missing from it.

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { readdirSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const CLI_ROOT = join(__dirname, '..', '..');
const MANIFEST = join(CLI_ROOT, 'oclif.manifest.json');

/** Commands whose source declares positional args, by oclif id. */
function commandsDeclaringArgs(dir = join(CLI_ROOT, 'src', 'commands'), prefix = ''): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (entry.isDirectory()) return commandsDeclaringArgs(join(dir, entry.name), `${prefix}${entry.name}:`);
    if (!entry.name.endsWith('.ts')) return [];
    const source = readFileSync(join(dir, entry.name), 'utf-8');
    if (!/static override args\s*=/.test(source)) return [];
    return [`${prefix}${entry.name.replace(/\.ts$/, '')}`];
  });
}

describe('oclif manifest', () => {
  it('is generated by the build', () => {
    expect(
      existsSync(MANIFEST),
      'run `yarn build` in packages/cli — without the manifest, every command that takes a positional argument is unreachable',
    ).toBe(true);
  });

  it('records the args of every command that declares them', () => {
    const manifest = JSON.parse(readFileSync(MANIFEST, 'utf-8')) as {
      commands: Record<string, { args?: Record<string, unknown> }>;
    };
    const declared = commandsDeclaringArgs();
    expect(declared.length).toBeGreaterThan(5);

    const missing = declared.filter((id) => {
      const entry = manifest.commands[id];
      return !entry || Object.keys(entry.args ?? {}).length === 0;
    });
    expect(
      missing,
      'these commands declare positional args that the manifest does not record, so oclif will treat their arguments as command names',
    ).toEqual([]);
  });
});
