name: Add new issues to SRE board

on:
  issues:
    types: [opened]

permissions:
  issues: read

jobs:
  add-to-project:
    name: Add issue to Shielded SRE Board (Backlog)
    uses: shieldedtech/.github/.github/workflows/add-issue-to-project.yml@70648caf313acd9d28e785e69b5841951f122fa1
    secrets:
      PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
    with:
      project_number: 50
      project_owner: shieldedtech
